// Mocks generated by Mockito 5.4.6 from annotations
// in mastery/test/domain/services/session_planner_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mastery/data/services/supabase_data_service.dart' as _i2;
import 'package:mastery/domain/models/progress_stage.dart' as _i4;
import 'package:mastery/domain/services/telemetry_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SupabaseDataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseDataService extends _i1.Mock
    implements _i2.SupabaseDataService {
  MockSupabaseDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> getVocabulary(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getVocabulary, [userId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getVocabularyById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVocabularyById, [id]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> searchVocabulary(
    String? userId,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchVocabulary, [userId, query]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> countVocabulary(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#countVocabulary, [userId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> deleteVocabulary(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVocabulary, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getMeanings(String? vocabularyId) =>
      (super.noSuchMethod(
            Invocation.method(#getMeanings, [vocabularyId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getPrimaryMeaning(String? vocabularyId) =>
      (super.noSuchMethod(
            Invocation.method(#getPrimaryMeaning, [vocabularyId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<String>> getEnrichedVocabularyIds(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnrichedVocabularyIds, [userId]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<Map<String, String>> getAllPrimaryTranslations(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPrimaryTranslations, [userId]),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<void> updateMeaning({
    required String? id,
    String? primaryTranslation,
    String? englishDefinition,
    String? partOfSpeech,
    List<String>? synonyms,
    List<String>? alternativeTranslations,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMeaning, [], {
              #id: id,
              #primaryTranslation: primaryTranslation,
              #englishDefinition: englishDefinition,
              #partOfSpeech: partOfSpeech,
              #synonyms: synonyms,
              #alternativeTranslations: alternativeTranslations,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getSessionCards(
    String? userId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionCards, [userId], {#limit: limit}),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getLearningCards(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getLearningCards, [userId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getLearningCardById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getLearningCardById, [id]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> getLearningCardByVocabularyId(
    String? userId,
    String? vocabularyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLearningCardByVocabularyId, [
              userId,
              vocabularyId,
            ]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<int> getNonTranslationSuccessCount(String? learningCardId) =>
      (super.noSuchMethod(
            Invocation.method(#getNonTranslationSuccessCount, [learningCardId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getDueCards(
    String? userId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDueCards, [userId], {#limit: limit}),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> getOverdueCount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueCount, [userId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getNewCards(
    String? userId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNewCards, [userId], {#limit: limit}),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getLeechCards(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getLeechCards, [userId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> countEnrichedNewWords(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#countEnrichedNewWords, [userId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> updateLearningCard({
    required String? cardId,
    required int? state,
    required DateTime? due,
    required double? stability,
    required double? difficulty,
    required int? reps,
    required int? lapses,
    required bool? isLeech,
    String? progressStage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateLearningCard, [], {
              #cardId: cardId,
              #state: state,
              #due: due,
              #stability: stability,
              #difficulty: difficulty,
              #reps: reps,
              #lapses: lapses,
              #isLeech: isLeech,
              #progressStage: progressStage,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<_i4.ProgressStage, int>> getVocabularyStageCounts(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVocabularyStageCounts, [userId]),
            returnValue: _i3.Future<Map<_i4.ProgressStage, int>>.value(
              <_i4.ProgressStage, int>{},
            ),
          )
          as _i3.Future<Map<_i4.ProgressStage, int>>);

  @override
  _i3.Future<void> insertReviewLog({
    required String? id,
    required String? userId,
    required String? learningCardId,
    required int? rating,
    required int? interactionMode,
    required int? stateBefore,
    required int? stateAfter,
    required double? stabilityBefore,
    required double? stabilityAfter,
    required double? difficultyBefore,
    required double? difficultyAfter,
    required int? responseTimeMs,
    required double? retrievabilityAtReview,
    String? sessionId,
    String? cueType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertReviewLog, [], {
              #id: id,
              #userId: userId,
              #learningCardId: learningCardId,
              #rating: rating,
              #interactionMode: interactionMode,
              #stateBefore: stateBefore,
              #stateAfter: stateAfter,
              #stabilityBefore: stabilityBefore,
              #stabilityAfter: stabilityAfter,
              #difficultyBefore: difficultyBefore,
              #difficultyAfter: difficultyAfter,
              #responseTimeMs: responseTimeMs,
              #retrievabilityAtReview: retrievabilityAtReview,
              #sessionId: sessionId,
              #cueType: cueType,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getActiveSession(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSession, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>> createSession({
    required String? id,
    required String? userId,
    required int? plannedMinutes,
    required DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [], {
              #id: id,
              #userId: userId,
              #plannedMinutes: plannedMinutes,
              #expiresAt: expiresAt,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> updateSessionProgress({
    required String? sessionId,
    required int? elapsedSeconds,
    required int? itemsPresented,
    required int? itemsCompleted,
    required int? newWordsPresented,
    required int? reviewsPresented,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSessionProgress, [], {
              #sessionId: sessionId,
              #elapsedSeconds: elapsedSeconds,
              #itemsPresented: itemsPresented,
              #itemsCompleted: itemsCompleted,
              #newWordsPresented: newWordsPresented,
              #reviewsPresented: reviewsPresented,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> endSession({
    required String? sessionId,
    required int? outcome,
    double? accuracyRate,
    int? avgResponseTimeMs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#endSession, [], {
              #sessionId: sessionId,
              #outcome: outcome,
              #accuracyRate: accuracyRate,
              #avgResponseTimeMs: avgResponseTimeMs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addBonusTime({
    required String? sessionId,
    required int? bonusSeconds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addBonusTime, [], {
              #sessionId: sessionId,
              #bonusSeconds: bonusSeconds,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getNewCardCount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getNewCardCount, [userId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<({double? accuracyPercent, int itemsReviewed})?>
  getTodaySessionStats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodaySessionStats, [userId]),
            returnValue:
                _i3.Future<
                  ({double? accuracyPercent, int itemsReviewed})?
                >.value(),
          )
          as _i3.Future<({double? accuracyPercent, int itemsReviewed})?>);

  @override
  _i3.Future<DateTime?> getNextDueDate(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getNextDueDate, [userId]),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<Map<String, dynamic>> getOrCreatePreferences(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreatePreferences, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> updatePreferences({
    required String? userId,
    int? dailyTimeTargetMinutes,
    double? targetRetention,
    int? intensity,
    bool? newWordSuppressionActive,
    String? nativeLanguageCode,
    String? meaningDisplayMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferences, [], {
              #userId: userId,
              #dailyTimeTargetMinutes: dailyTimeTargetMinutes,
              #targetRetention: targetRetention,
              #intensity: intensity,
              #newWordSuppressionActive: newWordSuppressionActive,
              #nativeLanguageCode: nativeLanguageCode,
              #meaningDisplayMode: meaningDisplayMode,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getOrCreateStreak(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateStreak, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> updateStreak({
    required String? id,
    required int? currentCount,
    required int? longestCount,
    DateTime? lastCompletedDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStreak, [], {
              #id: id,
              #currentCount: currentCount,
              #longestCount: longestCount,
              #lastCompletedDate: lastCompletedDate,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getMostRecentEncounter(
    String? vocabularyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMostRecentEncounter, [vocabularyId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getEncounters(String? vocabularyId) =>
      (super.noSuchMethod(
            Invocation.method(#getEncounters, [vocabularyId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getSourceById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSourceById, [id]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getCuesForVocabulary(
    String? vocabularyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCuesForVocabulary, [vocabularyId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getCuesForMeaning(String? meaningId) =>
      (super.noSuchMethod(
            Invocation.method(#getCuesForMeaning, [meaningId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> updateCue(
    String? cueId, {
    String? promptText,
    String? answerText,
    String? hintText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateCue,
              [cueId],
              {
                #promptText: promptText,
                #answerText: answerText,
                #hintText: hintText,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getConfusableSetsForVocabulary(
    String? vocabularyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConfusableSetsForVocabulary, [vocabularyId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> createMeaningEdit({
    required String? id,
    required String? userId,
    required String? meaningId,
    required String? fieldName,
    required String? originalValue,
    required String? userValue,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMeaningEdit, [], {
              #id: id,
              #userId: userId,
              #meaningId: meaningId,
              #fieldName: fieldName,
              #originalValue: originalValue,
              #userValue: userValue,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createEnrichmentFeedback({
    required String? userId,
    required String? meaningId,
    required String? fieldName,
    required String? rating,
    String? flagCategory,
    String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEnrichmentFeedback, [], {
              #userId: userId,
              #meaningId: meaningId,
              #fieldName: fieldName,
              #rating: rating,
              #flagCategory: flagCategory,
              #comment: comment,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getEnrichmentFeedback(
    String? meaningId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEnrichmentFeedback, [meaningId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getEnrichmentQueueStatus(
    String? userId,
    String? vocabularyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEnrichmentQueueStatus, [
              userId,
              vocabularyId,
            ]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<int> getReviewCount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewCount, [userId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<double> getAverageResponseTime(
    String? userId, {
    int? windowSize = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAverageResponseTime,
              [userId],
              {#windowSize: windowSize},
            ),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<void> createReviewLog({
    required String? id,
    required String? sessionId,
    required String? learningCardId,
    required int? rating,
    required int? responseTimeMs,
    required String? userId,
    int? oldState,
    int? newState,
    double? oldStability,
    double? newStability,
    double? oldDifficulty,
    double? newDifficulty,
    DateTime? oldDue,
    DateTime? newDue,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReviewLog, [], {
              #id: id,
              #sessionId: sessionId,
              #learningCardId: learningCardId,
              #rating: rating,
              #responseTimeMs: responseTimeMs,
              #userId: userId,
              #oldState: oldState,
              #newState: newState,
              #oldStability: oldStability,
              #newStability: newStability,
              #oldDifficulty: oldDifficulty,
              #newDifficulty: newDifficulty,
              #oldDue: oldDue,
              #newDue: newDue,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [TelemetryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTelemetryService extends _i1.Mock implements _i5.TelemetryService {
  MockTelemetryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<double> getEstimatedSecondsPerItem(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEstimatedSecondsPerItem, [userId]),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<int> estimateSessionCapacity({
    required String? userId,
    required int? timeMinutes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#estimateSessionCapacity, [], {
              #userId: userId,
              #timeMinutes: timeMinutes,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> estimateSessionDuration({
    required String? userId,
    required int? itemCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#estimateSessionDuration, [], {
              #userId: userId,
              #itemCount: itemCount,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
