# Strict Dart analyzer configuration for Mastery
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/data/database/database.g.dart"

linter:
  rules:
    # Error prevention
    avoid_print: true
    avoid_dynamic_calls: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    throw_in_finally: true
    unnecessary_statements: true

    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true

    # Documentation
    public_member_api_docs: false # Enable for library packages

    # Flutter specific
    use_key_in_widget_constructors: true
    prefer_const_constructors_in_immutables: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
