targets:
  $default:
    builders:
      drift_dev:
        options:
          scoped_dart_components: true
          store_date_time_values_as_text: true
          named_parameters: true
          named_parameters_always_required: false
          data_class_to_companions: true
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
      freezed:
        options:
          union_key: type
